### ISSUE TITLE
Mistake in self-checking tests

### ISSUE THREAD

**Issue by Rtchaik** [Philippe-Cholet/checkio-mission-find-rectangles#3]
Despite the fact that I've solved this mission and my code works for real tests I have the following mistake during self-checking:

You failed the test #1:
(1, 2, 3, 2) does not represent a rectangle, it should be a tuple/list of four integers.

**Comment by Philippe-Cholet** [comment]
I think I does not have enough informations to figure out what's wrong for you there (since it is clearly a tuple of four integers, so it's a rectangle).
The message the checker gives is supposed to help you, but is not enough for me.
I suggest you to print your entire result and paste it here.

**Important:** From "self-checking", I suppose when clicking "Run" from the online editor. And not clicking "Check". Behavior can be slightly different.

If knowing your entire result is not enough, I would probably need your code to replicate the error and see what's really wrong.

**Note:** If you used something like numpy/scipy/... to get these integers, it could be a problem, numpy as it own type of integers. It should not be a problem when clicking "Check" but it can be a problem when clicking "Run".

**Comment by Rtchaik** [comment]
Here is my code:
https://py.checkio.org/mission/find-rectangles/publications/r_tchaik/python-3/memoization-sorting-and-dfs/
I've used numpy, so maybe that's the problem.

**Comment by Philippe-Cholet** [comment]
Yes numpy is the problem here, as expected. I added `print(*map(type, rect))` before the assertion that goes wrong and it confirmed it.
I replaced the last line by

    result = dfs(my_grid, rectangles_all, set())
    return {tuple(map(int, rect)) for rect in result}
And everything is fine.

I helped oduvan improve the "Check" part, meaning we can return numpy types in "Check" part, but it can not help with "Run" part.
I suppose I could import numpy for the checker to check if integers are python ints or numpy ints, or use some trick like `or ('numpy' in str(type(coord)) and isinstance(coord.item(), int))`. But if everytime I write a checker (which is often) I need to check all numpy types, it is going to be painful.
Maybe I could write some function to transform any numpy user result to usual python result and then give it to the checker, I would not have to think about it in the checker.
Obviously, I could weaken the checker to not check if numbers are integers, clearly the easiest fix. But tomorrow, I could have somebody giving a numpy grid of four integers for a rectangle, instead of a list/tuple.

I think that at some point, we all (checkio users) have some problem with numpy having its own types.

What do you think I should do?

**Comment by Rtchaik** [comment]
It's not your fault. So maybe it will be enough to mention at the beginning of the error message that the checker does not work with numpy.

**Comment by Philippe-Cholet** [comment]
Not a single checker does any numpy check (unless obviously required, which I think is never the case), and "Check" part handles it well.
I just added a comment about that in [most common mistakes](https://py.checkio.org/forum/post/3269/6-the-most-common-mistakes/#comment-86863). The [FAQ](https://py.checkio.org/forum/post/3271/faq/) we see at the top of the forum links to these "common mistakes".
I think it is more appropriate than mention this in every checker.
So for me, the case is closed!

**Comment by Rtchaik** [comment]
That's fine!
